Milestone3 game logic
Ahmed-Benj/Tic-Tac-Toe pull request #4
Opened 2021-05-29 23:09 UTC by Ahmed-Benj

Hello,

In this milestone I have added a the game logic to the lib folder and included the methods :

1. won
2. full board
3. position taken check
4. WINCOMBINATIONS

Could you please review my project so far ?

Kind regards,

2021-05-30 00:42 UTC, elisha2kyakpo1 requested changes
# Status: Approved💪✔🎉
Hey @Ahmed-Benj, you have done a good job so far. However, there is room for improvement.

- [ ] Fix the rubocop errors
- [ ] I have seen useless files .vscode, .gitkeep in your project, please remove/delete them.
- [ ] Why do you have two files in bin folder? just maintain one with the latest code.
- [ ] No puts/print and gets.chomp outside main.rb file.
- [ ] Use require_relate instead of require.
- [ ] The code of the project should be logically divided between classes. Create at least two classes in lib folder to accommodate your lib folder code ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

<hr>
[OPTIONAL]

- [ ] The game accepts numbers for a player name. You can make validations for this as well.

<hr>
You can reach me on slack by searching my name as Elisha kyakopo in case you have a question.

Happy coding💪👈

2021-05-30 00:42 UTC, elisha2kyakpo1 commented on bin/main.rb
> +
Use require_relative instead of require

2021-05-30 00:42 UTC, elisha2kyakpo1 commented on bin/main.rb
> -  board
No puts outside main.rb file

2021-05-30 11:32 UTC, Ahmed-Benj commented on bin/main.rb
> -  board
> No puts outside main.rb file

Fixed

2021-05-30 11:33 UTC, Ahmed-Benj commented on bin/main.rb
> +
> Use require_relative instead of require

Fixed

2021-05-30 13:44 UTC, Ahmed-Benj commented
Hello @elisha2kyakpo1 ,

Thank you for these comments.

I have made the requested changes, could you please re-review my project.

Kind regards,
Ahmed

2021-05-30 14:03 UTC, elisha2kyakpo1 requested changes
# Status: Changes required👈
Hey @Ahmed-Benj, I'm happy to see almost all the changes requested being implemented, just one issue has prevented this project from being approved.

- [ ] The code of the project should be logically divided between classes. Create at least two classes in lib folder to accommodate your lib folder code (screenshot from Pathwright)

That's it, make the change and request for a review.

Once again, you can reach me on slack by searching Elisha kyakopo, in case you have a question.

Cheers🎉✔💪

2021-05-31 22:44 UTC, Ahmed-Benj commented
I couldn't find a way to add another class in the lib folder, I don't know why I would need that in my solution, 

could you please approve my project ?

Kind regards,

2021-06-01 00:27 UTC, BrianSammit approved these changes
STATUS: APPROVED :green_circle: :clap: 
---------
Hello @Ahmed-Benj  Great job you did on the required changes :clap: :muscle: 
The project is working really nice :+1:  good job :1st_place_medal: 
--------
Now you can merge this branch :100: :smile: 
HAPPY CODING!! AND GOOD LUCK WITH THE COMMING MILESTONE :crossed_fingers: :four_leaf_clover:

![tenor](https://user-images.githubusercontent.com/64173189/120251116-13c35600-c246-11eb-8cc4-1091bf055637.gif)

2021-06-01 09:36 UTC, Ahmed-Benj commented
> ## STATUS: APPROVED 🟢 👏
> ## Hello @Ahmed-Benj Great job you did on the required changes 👏 💪
> The project is working really nice 👍 good job 🥇
> Now you can merge this branch 💯 😄
> HAPPY CODING!! AND GOOD LUCK WITH THE COMMING MILESTONE 🤞 🍀
> 
> ![tenor](https://user-images.githubusercontent.com/64173189/120251116-13c35600-c246-11eb-8cc4-1091bf055637.gif)

Hello Brian, thanks for the review!

2021-06-01 11:40 UTC, merged